### ISSUE TITLE
Failed to open lib on macOS ARM

### ISSUE THREAD

**Issue by DuGBT** [microsoft/vscode-policy-watcher#9]
I am trying to compile vscode on M1 Pro Macbook following the official guide. The first two-step install the dependencies and compile locally is done, running 'yarn' and 'yarn watch'. But running the third step,'./scripts/code.sh',goes to an error. How should I fix it? reinstall some dependencies or rebuild some package manually? I hope someone can answer me 

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/29980115/178561874-545d79af-76ba-41cb-947f-78715ff3a87c.png">

**Comment by joaomoreno** [comment]
Is this still an issue?

**Comment by joaomoreno** [comment]
Can you retry compiling everything?

```
git clean -xfd .
yarn
```

**Comment by PEZ** [comment]
I'm also getting this trying to build vscode on a Macbook Pro M4 Max. The @vscode/policy-watcher dependency is `^1.1.4`, and trying to use anything newer results in incompatible node version errors. I'm using node 16.18.0 because going to 17 or above seems to not be supported by the vscode build.

**Comment by joaomoreno** [comment]
Closing this for now.

@PEZ are you looking into debugging VS Code? If so, you don't have to build it. Simply run `npm i` and press F5 inside VS Code.

**Comment by PEZ** [comment]
Thanks. I was hacking on thing so needed to build. Never figured out a way to run it in the debugger unfortunately, so it was a bit painful. Eventually concluded that Electron won't allow the feature I was experimenting with, so have dropped the idea. 😀
